version: '3.8'

services:
  workshop:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password}
    command: server --console-address ":9001" /data

  lakefs:
    build:
      context: ./docker/services/lakefs
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    environment:
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=${LAKEFS_AUTH_ENCRYPT_SECRET_KEY:-some random secret string}
      - LAKEFS_DATABASE_TYPE=${LAKEFS_DATABASE_TYPE:-postgres}
      - LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING=${LAKEFS_DATABASE_POSTGRES_CONNECTION_STRING:-postgres://lakefs:lakefs@postgres/postgres?sslmode=disable}
      - LAKEFS_BLOCKSTORE_TYPE=${LAKEFS_BLOCKSTORE_TYPE:-local}
      - LAKEFS_BLOCKSTORE_LOCAL_PATH=${LAKEFS_BLOCKSTORE_LOCAL_PATH:-/home/lakefs}
      - LAKEFS_GATEWAYS_S3_DOMAIN_NAME=${LAKEFS_GATEWAYS_S3_DOMAIN_NAME:-s3.local.lakefs.io:8000}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - LAKEFS_LOGGING_LEVEL=${LAKEFS_LOGGING_LEVEL:-INFO}
      - LAKEFS_STATS_ENABLED
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE
      - LAKEFS_COMMITTED_LOCAL_CACHE_DIR=${LAKEFS_COMMITTED_LOCAL_CACHE_DIR:-/home/lakefs/.local_tier}
    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]

  postgres:
    image: "postgres:${PG_VERSION:-11}"
    command: "-c log_min_messages=FATAL"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
    logging:
      driver: none

  loki:
    image: grafana/loki:v1.3.0

  prometheus:
    build:
      context: ./docker/services/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.local.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  # Root node is enabled by setting an empty seed [REDPANDA_SEEDS]
  # - Only 1 root node is allowed in the cluster
  redpanda-broker-1:
    build:
      context: ./docker/services/redpanda_broker
    hostname: redpanda-broker-1
    volumes:
      - "redpanda_broker_1_data:/var/lib/redpanda/data"
    environment:
      - NODE_ID=1
      - ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST=redpanda-broker-1
      - ADVERTISE_RPC_ADDR_HOST=redpanda-broker-1

  redpanda-broker-2:
    build:
      context: ./docker/services/redpanda_broker
    hostname: redpanda-broker-2
    volumes:
      - "redpanda_broker_2_data:/var/lib/redpanda/data"
    environment:
      - NODE_ID=2
      - REDPANDA_SEEDS=redpanda-broker-1:33145
      - ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST=redpanda-broker-2
      - ADVERTISE_RPC_ADDR_HOST=redpanda-broker-2

  redpanda-broker-3:
    build:
      context: ./docker/services/redpanda_broker
    hostname: redpanda-broker-3
    volumes:
      - "redpanda_broker_3_data:/var/lib/redpanda/data"
    environment:
      - NODE_ID=3
      - REDPANDA_SEEDS=redpanda-broker-1:33145
      - ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST=redpanda-broker-3
      - ADVERTISE_RPC_ADDR_HOST=redpanda-broker-3

  redpanda-console:
    build:
      context: ./docker/services/redpanda_console
    depends_on:
      - redpanda-broker-1
      - redpanda-broker-2
      - redpanda-broker-3
    environment:
      - KAFKA_BROKERS=redpanda-broker-1:29092,redpanda-broker-2:29092,redpanda-broker-3:29092
      - KAFKA_SCHEMA_REGISTRY_URLS=http://redpanda-broker-1:8081,http://redpanda-broker-2:8081,http://redpanda-broker-3:8081
      - REDPANDA_ADMIN_API_URLS=http://redpanda-broker-1:9644,http://redpanda-broker-2:9644,http://redpanda-broker-3:9644

  clickhouse:
    build:
      context: ./docker/services/clickhouse
    ports:
      - 8123:8123
      - 9000:9000

  grafana:
    build:
      context: ./docker/services/grafana

  reverse-proxy:
    build:
      context: ./docker/services/reverse_proxy
    ports:
      - 80:8080
    environment:
      - REDPANDA_CONSOLE_INTERNAL_HOST=redpanda-console

volumes:
  minio_data:
  prometheus_data:
  redpanda_broker_1_data:
  redpanda_broker_2_data:
  redpanda_broker_3_data:
  grafana_data:
