FROM docker.redpanda.com/vectorized/redpanda:v22.3.11
ENV NODE_ID=${NODE_ID:-0}
ENV KAFKA_ADDR_PLAINTEXT_HOST=${KAFKA_ADDR_PLAINTEXT_HOST:-0.0.0.0}
ENV KAFKA_ADDR_PLAINTEXT_PORT=${KAFKA_ADDR_PLAINTEXT_PORT:-29092}
ENV KAFKA_ADDR_OUTSIDE_HOST=${KAFKA_ADDR_OUTSIDE_HOST:-0.0.0.0}
ENV KAFKA_ADDR_OUTSIDE_PORT=${KAFKA_ADDR_OUTSIDE_PORT:-9092}
ENV ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST=${ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST:-redpanda-broker}
ENV ADVERTISE_KAFKA_ADDR_PLAINTEXT_PORT=${ADVERTISE_KAFKA_ADDR_PLAINTEXT_PORT:-29092}
ENV ADVERTISE_KAFKA_ADDR_OUTSIDE_HOST=${ADVERTISE_KAFKA_ADDR_OUTSIDE_HOST:-localhost}
ENV ADVERTISE_KAFKA_ADDR_OUTSIDE_PORT=${ADVERTISE_KAFKA_ADDR_OUTSIDE_PORT:-9092}
ENV RPC_ADDR_HOST=${RPC_ADDR_HOST:-0.0.0.0}
ENV RPC_ADDR_PORT=${RPC_ADDR_PORT:-33145}
ENV ADVERTISE_RPC_ADDR_HOST=${ADVERTISE_RPC_ADDR_HOST:-redpanda-broker-core}
ENV ADVERTISE_RPC_ADDR_PORT=${ADVERTISE_RPC_ADDR_PORT:-33145}
ENV PANDAPROXY_ADDR_HOST=${PANDAPROXY_ADDR_HOST:-0.0.0.0}
ENV PANDAPROXY_ADDR_PORT=${PANDAPROXY_ADDR_PORT:-8082}
ENV ADVERTISE_PANDAPROXY_ADDR_HOST=${ADVERTISE_PANDAPROXY_ADDR_HOST:-localhost}
ENV ADVERTISE_PANDAPROXY_ADDR_PORT=${ADVERTISE_PANDAPROXY_ADDR_PORT:-8082}

EXPOSE 33145

ENTRYPOINT []
CMD exec /entrypoint.sh \
    redpanda \
    start \
    --smp 1 \
    --overprovisioned \
    --node-id ${NODE_ID} \
    --kafka-addr PLAINTEXT://${KAFKA_ADDR_PLAINTEXT_HOST}:${KAFKA_ADDR_PLAINTEXT_PORT},OUTSIDE://${KAFKA_ADDR_OUTSIDE_HOST}:${KAFKA_ADDR_OUTSIDE_PORT} \
    --advertise-kafka-addr PLAINTEXT://${ADVERTISE_KAFKA_ADDR_PLAINTEXT_HOST}:${ADVERTISE_KAFKA_ADDR_PLAINTEXT_PORT},OUTSIDE://${ADVERTISE_KAFKA_ADDR_OUTSIDE_HOST}:${ADVERTISE_KAFKA_ADDR_OUTSIDE_PORT} \
    --rpc-addr ${RPC_ADDR_HOST}:${RPC_ADDR_PORT} \
    --advertise-rpc-addr ${ADVERTISE_RPC_ADDR_HOST}:${ADVERTISE_RPC_ADDR_PORT} \
    --pandaproxy-addr ${PANDAPROXY_ADDR_HOST}:${PANDAPROXY_ADDR_PORT} \
    --advertise-pandaproxy-addr ${ADVERTISE_PANDAPROXY_ADDR_HOST}:${ADVERTISE_PANDAPROXY_ADDR_PORT}
